language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
- npm run build
notifications:
  email: false
  slack:
    secure: gabJFxp2eCYVKNUFNCyBSWF88CDx7Paec2ujs4el2Fb7CatSL9rmfhhQpBtTzz/BFHCgIYVBy/4aFwfqFIRmQlxIrRe4jaz5YvNtVc5GK3tOq2GFyKMLdVqUeyX1t1ZNXr99CpXi1SYujxtGhVzDAcM9xDYOmsFytZH/n++mSmGYIo1nXjko6KHWqPi7OGJlpaLgEQM9N9C0LMsGUaH/zysLHNtx3pooPqGg2gRl2LIOdTDwVWb6oBvs4c0nps9gTGWbYX0T477mQQvMKVmUYiZXijPSF7IUspmVOF1erZO8CCuRq4BeqmagjrgcRd2FFpy4QhOnKkHamMY31+aBviAzV8RdfDn4I16dJS3x+kLX+mLn10mOaMEF8bnQe/MfGYI9n+kalwx7iEfEjI5Aoj77dYLYma0PjYHRE3TJZkEJWc0Oy+q2hudZ2CAuNvu7jO9RrVfb5gmY+9MD10M4k+uXfqVplF0pJGKF2lrAmbDx5mtAMO2ZhsiGRilCEqH7VCe7PjZDKXQVqe1vfmscES3BwVfZJJIDTKuCps+aKKlHzN1h9rQ5josKpfWxWzSmkteERExyFBIr6ivFA3BkDIAxx5mJ2JVsO8VYpa5zmN4rtgVOVUaFYHwmXZhWbDZx+1L35rcMgKdtfYw6/Kw8nU2kBaMLZc//kc173HR2Kgs=
deploy:
  provider: npm
  email: deptno@gmail.com
  api_key:
    secure: plzssqkyzUOcTEMoLMUPE7t32ioeywMqWQlm9bAtYw+HAgTnmeGJvcc+VnLREqb/cHuk2EpKvVGx2iwivFjXY5KT/cbCaniNWIEgko24+cacr6sRVn9jqqP5UtWOd8yT7MTJAJV2A7NXTKJIQDElxQRPGxahGtL7JBjHb7l+alXY3sAzW+wRX4M5CqYkRp83OrQI1HdKll/MBL4OXk1PhmDBGO/TSg4Mf2eo62htKq8NRS+TxYTUp/807tMe7SGTQvqyzl9GQzsrPuK5q0YLEXPDdsYVfaTc6/0vBgTgWPf3MN8Jmi1u5464tsM2n4sHeAijlR8+0DYMXjsHObqehu24ezknkAMbU6jPn8oHu0qAeLrC1D3AX+0qceePV1E2FDL87+iA8MpyinoQ2zHp9pcy/CvVlu8bYpJvrlJZK/iP5LMsfBjuIgwvsVHBg/h9BqKOv18GVAoVdWLhtctYhdSWBjaPRG7ClpbdMlXd9j6cwJ6dTWI5cc8hZv0LT6+S6B1+xQKvTJiJIrwBRMjjihoNqSz5q9UokrjyPPJa+96Xhu4jxT6S+fXL1+ksf02tH/Lbm8ORsktUBEjse+6rWzHXnJ3o3i1pJcbFJ4WINwABVk2fNsJlXITXHiKIycVq+bwLaUqrOFfphxxz/8W06jBAYrQUmCFmd9V29/xeh9A=
  on:
    tags: true
    repo: deptno/phantomjs-render-worker
